project_id = "zyzlmzfbuucpjdkhrfhg"

[functions.ares-lookup]
verify_jwt = false

[functions.invoice-assistant]
verify_jwt = false

[functions.get-stripe-price]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false
