/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZapomenuteHesloRouteImport } from './routes/zapomenute-heslo'
import { Route as SrovnaniRouteImport } from './routes/srovnani'
import { Route as ResetHeslaRouteImport } from './routes/reset-hesla'
import { Route as RegistraceRouteImport } from './routes/registrace'
import { Route as PrihlaseniRouteImport } from './routes/prihlaseni'
import { Route as PodminkyRouteImport } from './routes/podminky'
import { Route as NaseSlibyRouteImport } from './routes/nase-sliby'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as FunkceRouteImport } from './routes/funkce'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CenikRouteImport } from './routes/cenik'
import { Route as AkceRouteImport } from './routes/akce'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAppIndexRouteImport } from './routes/_app.app.index'
import { Route as AppAppOnboardingRouteImport } from './routes/_app.app.onboarding'
import { Route as AppAppNastaveniRouteImport } from './routes/_app.app.nastaveni'
import { Route as AppAppKlientiRouteImport } from './routes/_app.app.klienti'
import { Route as AppAppPredplatneIndexRouteImport } from './routes/_app.app.predplatne.index'
import { Route as AppAppFakturyIndexRouteImport } from './routes/_app.app.faktury.index'
import { Route as AppAppPredplatneDekujemeRouteImport } from './routes/_app.app.predplatne.dekujeme'
import { Route as AppAppFakturyEditorRouteImport } from './routes/_app.app.faktury.editor'

const ZapomenuteHesloRoute = ZapomenuteHesloRouteImport.update({
  id: '/zapomenute-heslo',
  path: '/zapomenute-heslo',
  getParentRoute: () => rootRouteImport,
} as any)
const SrovnaniRoute = SrovnaniRouteImport.update({
  id: '/srovnani',
  path: '/srovnani',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetHeslaRoute = ResetHeslaRouteImport.update({
  id: '/reset-hesla',
  path: '/reset-hesla',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistraceRoute = RegistraceRouteImport.update({
  id: '/registrace',
  path: '/registrace',
  getParentRoute: () => rootRouteImport,
} as any)
const PrihlaseniRoute = PrihlaseniRouteImport.update({
  id: '/prihlaseni',
  path: '/prihlaseni',
  getParentRoute: () => rootRouteImport,
} as any)
const PodminkyRoute = PodminkyRouteImport.update({
  id: '/podminky',
  path: '/podminky',
  getParentRoute: () => rootRouteImport,
} as any)
const NaseSlibyRoute = NaseSlibyRouteImport.update({
  id: '/nase-sliby',
  path: '/nase-sliby',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const FunkceRoute = FunkceRouteImport.update({
  id: '/funkce',
  path: '/funkce',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CenikRoute = CenikRouteImport.update({
  id: '/cenik',
  path: '/cenik',
  getParentRoute: () => rootRouteImport,
} as any)
const AkceRoute = AkceRouteImport.update({
  id: '/akce',
  path: '/akce',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppOnboardingRoute = AppAppOnboardingRouteImport.update({
  id: '/app/onboarding',
  path: '/app/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppAppNastaveniRoute = AppAppNastaveniRouteImport.update({
  id: '/app/nastaveni',
  path: '/app/nastaveni',
  getParentRoute: () => AppRoute,
} as any)
const AppAppKlientiRoute = AppAppKlientiRouteImport.update({
  id: '/app/klienti',
  path: '/app/klienti',
  getParentRoute: () => AppRoute,
} as any)
const AppAppPredplatneIndexRoute = AppAppPredplatneIndexRouteImport.update({
  id: '/app/predplatne/',
  path: '/app/predplatne/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppFakturyIndexRoute = AppAppFakturyIndexRouteImport.update({
  id: '/app/faktury/',
  path: '/app/faktury/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppPredplatneDekujemeRoute =
  AppAppPredplatneDekujemeRouteImport.update({
    id: '/app/predplatne/dekujeme',
    path: '/app/predplatne/dekujeme',
    getParentRoute: () => AppRoute,
  } as any)
const AppAppFakturyEditorRoute = AppAppFakturyEditorRouteImport.update({
  id: '/app/faktury/editor',
  path: '/app/faktury/editor',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/akce': typeof AkceRoute
  '/cenik': typeof CenikRoute
  '/faq': typeof FaqRoute
  '/funkce': typeof FunkceRoute
  '/gdpr': typeof GdprRoute
  '/nase-sliby': typeof NaseSlibyRoute
  '/podminky': typeof PodminkyRoute
  '/prihlaseni': typeof PrihlaseniRoute
  '/registrace': typeof RegistraceRoute
  '/reset-hesla': typeof ResetHeslaRoute
  '/srovnani': typeof SrovnaniRoute
  '/zapomenute-heslo': typeof ZapomenuteHesloRoute
  '/app/klienti': typeof AppAppKlientiRoute
  '/app/nastaveni': typeof AppAppNastaveniRoute
  '/app/onboarding': typeof AppAppOnboardingRoute
  '/app/': typeof AppAppIndexRoute
  '/app/faktury/editor': typeof AppAppFakturyEditorRoute
  '/app/predplatne/dekujeme': typeof AppAppPredplatneDekujemeRoute
  '/app/faktury/': typeof AppAppFakturyIndexRoute
  '/app/predplatne/': typeof AppAppPredplatneIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/akce': typeof AkceRoute
  '/cenik': typeof CenikRoute
  '/faq': typeof FaqRoute
  '/funkce': typeof FunkceRoute
  '/gdpr': typeof GdprRoute
  '/nase-sliby': typeof NaseSlibyRoute
  '/podminky': typeof PodminkyRoute
  '/prihlaseni': typeof PrihlaseniRoute
  '/registrace': typeof RegistraceRoute
  '/reset-hesla': typeof ResetHeslaRoute
  '/srovnani': typeof SrovnaniRoute
  '/zapomenute-heslo': typeof ZapomenuteHesloRoute
  '/app/klienti': typeof AppAppKlientiRoute
  '/app/nastaveni': typeof AppAppNastaveniRoute
  '/app/onboarding': typeof AppAppOnboardingRoute
  '/app': typeof AppAppIndexRoute
  '/app/faktury/editor': typeof AppAppFakturyEditorRoute
  '/app/predplatne/dekujeme': typeof AppAppPredplatneDekujemeRoute
  '/app/faktury': typeof AppAppFakturyIndexRoute
  '/app/predplatne': typeof AppAppPredplatneIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/akce': typeof AkceRoute
  '/cenik': typeof CenikRoute
  '/faq': typeof FaqRoute
  '/funkce': typeof FunkceRoute
  '/gdpr': typeof GdprRoute
  '/nase-sliby': typeof NaseSlibyRoute
  '/podminky': typeof PodminkyRoute
  '/prihlaseni': typeof PrihlaseniRoute
  '/registrace': typeof RegistraceRoute
  '/reset-hesla': typeof ResetHeslaRoute
  '/srovnani': typeof SrovnaniRoute
  '/zapomenute-heslo': typeof ZapomenuteHesloRoute
  '/_app/app/klienti': typeof AppAppKlientiRoute
  '/_app/app/nastaveni': typeof AppAppNastaveniRoute
  '/_app/app/onboarding': typeof AppAppOnboardingRoute
  '/_app/app/': typeof AppAppIndexRoute
  '/_app/app/faktury/editor': typeof AppAppFakturyEditorRoute
  '/_app/app/predplatne/dekujeme': typeof AppAppPredplatneDekujemeRoute
  '/_app/app/faktury/': typeof AppAppFakturyIndexRoute
  '/_app/app/predplatne/': typeof AppAppPredplatneIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/akce'
    | '/cenik'
    | '/faq'
    | '/funkce'
    | '/gdpr'
    | '/nase-sliby'
    | '/podminky'
    | '/prihlaseni'
    | '/registrace'
    | '/reset-hesla'
    | '/srovnani'
    | '/zapomenute-heslo'
    | '/app/klienti'
    | '/app/nastaveni'
    | '/app/onboarding'
    | '/app/'
    | '/app/faktury/editor'
    | '/app/predplatne/dekujeme'
    | '/app/faktury/'
    | '/app/predplatne/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/akce'
    | '/cenik'
    | '/faq'
    | '/funkce'
    | '/gdpr'
    | '/nase-sliby'
    | '/podminky'
    | '/prihlaseni'
    | '/registrace'
    | '/reset-hesla'
    | '/srovnani'
    | '/zapomenute-heslo'
    | '/app/klienti'
    | '/app/nastaveni'
    | '/app/onboarding'
    | '/app'
    | '/app/faktury/editor'
    | '/app/predplatne/dekujeme'
    | '/app/faktury'
    | '/app/predplatne'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/akce'
    | '/cenik'
    | '/faq'
    | '/funkce'
    | '/gdpr'
    | '/nase-sliby'
    | '/podminky'
    | '/prihlaseni'
    | '/registrace'
    | '/reset-hesla'
    | '/srovnani'
    | '/zapomenute-heslo'
    | '/_app/app/klienti'
    | '/_app/app/nastaveni'
    | '/_app/app/onboarding'
    | '/_app/app/'
    | '/_app/app/faktury/editor'
    | '/_app/app/predplatne/dekujeme'
    | '/_app/app/faktury/'
    | '/_app/app/predplatne/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AkceRoute: typeof AkceRoute
  CenikRoute: typeof CenikRoute
  FaqRoute: typeof FaqRoute
  FunkceRoute: typeof FunkceRoute
  GdprRoute: typeof GdprRoute
  NaseSlibyRoute: typeof NaseSlibyRoute
  PodminkyRoute: typeof PodminkyRoute
  PrihlaseniRoute: typeof PrihlaseniRoute
  RegistraceRoute: typeof RegistraceRoute
  ResetHeslaRoute: typeof ResetHeslaRoute
  SrovnaniRoute: typeof SrovnaniRoute
  ZapomenuteHesloRoute: typeof ZapomenuteHesloRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zapomenute-heslo': {
      id: '/zapomenute-heslo'
      path: '/zapomenute-heslo'
      fullPath: '/zapomenute-heslo'
      preLoaderRoute: typeof ZapomenuteHesloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/srovnani': {
      id: '/srovnani'
      path: '/srovnani'
      fullPath: '/srovnani'
      preLoaderRoute: typeof SrovnaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-hesla': {
      id: '/reset-hesla'
      path: '/reset-hesla'
      fullPath: '/reset-hesla'
      preLoaderRoute: typeof ResetHeslaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrace': {
      id: '/registrace'
      path: '/registrace'
      fullPath: '/registrace'
      preLoaderRoute: typeof RegistraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prihlaseni': {
      id: '/prihlaseni'
      path: '/prihlaseni'
      fullPath: '/prihlaseni'
      preLoaderRoute: typeof PrihlaseniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podminky': {
      id: '/podminky'
      path: '/podminky'
      fullPath: '/podminky'
      preLoaderRoute: typeof PodminkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nase-sliby': {
      id: '/nase-sliby'
      path: '/nase-sliby'
      fullPath: '/nase-sliby'
      preLoaderRoute: typeof NaseSlibyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funkce': {
      id: '/funkce'
      path: '/funkce'
      fullPath: '/funkce'
      preLoaderRoute: typeof FunkceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cenik': {
      id: '/cenik'
      path: '/cenik'
      fullPath: '/cenik'
      preLoaderRoute: typeof CenikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akce': {
      id: '/akce'
      path: '/akce'
      fullPath: '/akce'
      preLoaderRoute: typeof AkceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app/': {
      id: '/_app/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/onboarding': {
      id: '/_app/app/onboarding'
      path: '/app/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppAppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/nastaveni': {
      id: '/_app/app/nastaveni'
      path: '/app/nastaveni'
      fullPath: '/app/nastaveni'
      preLoaderRoute: typeof AppAppNastaveniRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/klienti': {
      id: '/_app/app/klienti'
      path: '/app/klienti'
      fullPath: '/app/klienti'
      preLoaderRoute: typeof AppAppKlientiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/predplatne/': {
      id: '/_app/app/predplatne/'
      path: '/app/predplatne'
      fullPath: '/app/predplatne/'
      preLoaderRoute: typeof AppAppPredplatneIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/faktury/': {
      id: '/_app/app/faktury/'
      path: '/app/faktury'
      fullPath: '/app/faktury/'
      preLoaderRoute: typeof AppAppFakturyIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/predplatne/dekujeme': {
      id: '/_app/app/predplatne/dekujeme'
      path: '/app/predplatne/dekujeme'
      fullPath: '/app/predplatne/dekujeme'
      preLoaderRoute: typeof AppAppPredplatneDekujemeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/faktury/editor': {
      id: '/_app/app/faktury/editor'
      path: '/app/faktury/editor'
      fullPath: '/app/faktury/editor'
      preLoaderRoute: typeof AppAppFakturyEditorRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAppKlientiRoute: typeof AppAppKlientiRoute
  AppAppNastaveniRoute: typeof AppAppNastaveniRoute
  AppAppOnboardingRoute: typeof AppAppOnboardingRoute
  AppAppIndexRoute: typeof AppAppIndexRoute
  AppAppFakturyEditorRoute: typeof AppAppFakturyEditorRoute
  AppAppPredplatneDekujemeRoute: typeof AppAppPredplatneDekujemeRoute
  AppAppFakturyIndexRoute: typeof AppAppFakturyIndexRoute
  AppAppPredplatneIndexRoute: typeof AppAppPredplatneIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppKlientiRoute: AppAppKlientiRoute,
  AppAppNastaveniRoute: AppAppNastaveniRoute,
  AppAppOnboardingRoute: AppAppOnboardingRoute,
  AppAppIndexRoute: AppAppIndexRoute,
  AppAppFakturyEditorRoute: AppAppFakturyEditorRoute,
  AppAppPredplatneDekujemeRoute: AppAppPredplatneDekujemeRoute,
  AppAppFakturyIndexRoute: AppAppFakturyIndexRoute,
  AppAppPredplatneIndexRoute: AppAppPredplatneIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AkceRoute: AkceRoute,
  CenikRoute: CenikRoute,
  FaqRoute: FaqRoute,
  FunkceRoute: FunkceRoute,
  GdprRoute: GdprRoute,
  NaseSlibyRoute: NaseSlibyRoute,
  PodminkyRoute: PodminkyRoute,
  PrihlaseniRoute: PrihlaseniRoute,
  RegistraceRoute: RegistraceRoute,
  ResetHeslaRoute: ResetHeslaRoute,
  SrovnaniRoute: SrovnaniRoute,
  ZapomenuteHesloRoute: ZapomenuteHesloRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
